# Generated by Django 3.2.9 on 2021-11-27 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0002_notebook_smartphone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notebook',
            old_name='time_vithout_charge',
            new_name='time_without_charge',
        ),
    ]
