# Generated by Django 3.2.9 on 2021-12-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0006_rename_product_cart_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='sd',
            field=models.BooleanField(default=True, verbose_name='Наличие SD карты'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='sd_volume_max',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Объем памяти мах.'),
        ),
    ]
